### ISSUE TITLE
Unable to get existing Amplify project up and running

### ISSUE THREAD

**Issue by dwamianm** [localstack/amplify-js-local#1] opened 2021-01-27 20:22 UTC
OS: Mac 10.15.7 (Catalina)
Amplify Version: 4.41.2
Python Version: 3.7.6 (w/pip3)

After signing up for professional and hours of trying to configure this with an existing amplify project I am still not able to get even a first push. The push works when pushing to an AWS stack but fails on localstack. 

For the most part the errors look like this with no real indication of what is wrong. Any help is appreciated

<pre>
Unable to update stack "amplify-jxnapp-local-133700": An error occurred (ValidationError) when calling the CreateStack operation: Unable to create stack "amplify-jxnapp-local-133700-hostingS3AndCloudFront-ebfe70be": Resource deployment loop completed, pending resource changes: [{'Type': 'Resource', 'ResourceChange': {'Action': 'Add', 'LogicalResourceId': 'CloudFrontDistribution', 'PhysicalResourceId': None, 'ResourceType': 'AWS::CloudFront::Distribution', 'Replacement': 'False', 'ChangeSetId': None}}, {'Type': 'Resource', 'ResourceChange': {'Action': 'Add', 'LogicalResourceId': 'PrivateBucketPolicy', 'PhysicalResourceId': None, 'ResourceType': 'AWS::S3::BucketPolicy', 'Replacement': 'False', 'ChangeSetId': None}}, {'Type': 'Resource', 'ResourceChange': {'Action': 'Modify', 'LogicalResourceId': 'CloudFrontDistribution', 'PhysicalResourceId': None, 'ResourceType': 'AWS::CloudFront::Distribution', 'Replacement': 'False', 'ChangeSetId': None}}, {'Type': 'Resource', 'ResourceChange': {'Action': 'Modify', 'LogicalResourceId': 'PrivateBucketPolicy', 'PhysicalResourceId': None, 'ResourceType': 'AWS::S3::BucketPolicy', 'Replacement': 'False', 'ChangeSetId': None}}]
An error occurred during the push operation: Unable to update stack "amplify-jxnapp-local-133700": An error occurred (ValidationError) when calling the CreateStack operation: Unable to create stack "amplify-jxnapp-local-133700-hostingS3AndCloudFront-ebfe70be": Resource deployment loop completed, pending resource changes: [{'Type': 'Resource', 'ResourceChange': {'Action': 'Add', 'LogicalResourceId': 'CloudFrontDistribution', 'PhysicalResourceId': None, 'ResourceType': 'AWS::CloudFront::Distribution', 'Replacement': 'False', 'ChangeSetId': None}}, {'Type': 'Resource', 'ResourceChange': {'Action': 'Add', 'LogicalResourceId': 'PrivateBucketPolicy', 'PhysicalResourceId': None, 'ResourceType': 'AWS::S3::BucketPolicy', 'Replacement': 'False', 'ChangeSetId': None}}, {'Type': 'Resource', 'ResourceChange': {'Action': 'Modify', 'LogicalResourceId': 'CloudFrontDistribution', 'PhysicalResourceId': None, 'ResourceType': 'AWS::CloudFront::Distribution', 'Replacement': 'False', 'ChangeSetId': None}}, {'Type': 'Resource', 'ResourceChange': {'Action': 'Modify', 'LogicalResourceId': 'PrivateBucketPolicy', 'PhysicalResourceId': None, 'ResourceType': 'AWS::S3::BucketPolicy', 'Replacement': 'False', 'ChangeSetId': None}}]
</pre>

**Comment by whummer** [comment] 2021-01-31 19:19
Hi @dwamianm thanks for reaching out. Can you please share some details about your use case? In case you cannot share here, please feel free to get in touch via email (info@localstack.cloud) or Slack to share you project - we'll be happy to look into it and get your use case deployed. Thanks for your help!

**Comment by whummer** [comment] 2022-12-09 15:35
Closing as "cannot reproduce" - please feel free to re-open this issue if the problem persists. If you can share some more details about your Amplify app, we'll be happy to look into it! 👍

**Closed as completed by whummer** 2022-12-09 15:35 UTC
